FROM nimmis/alpine-java
MAINTAINER limaofeng limaofeng@msn.com
RUN apk --update add bash
	&& apk --update add wget
	#wget --no-cookies --no-check-certificate --header "Cookie:gpw_e24=http%3a%2f%2fwww.oracle.com%2ftechnetwork%2fjava%2fjavase%2fdownloads%2fjdk8-downloads-2133151.html;oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u101-b13/jdk-8u101-linux-arm64-vfp-hflt.tar.gz &&
	#tar zxvf jdk-8u101-linux-x64.tar.gz  -C /usr/lib/ &&
	#export JAVA_HOME=/usr/lib/jdk1.8.0_101 &&
	#export JRE_HOME=${JAVA_HOME}/jre && 
	#export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib &&
	#export PATH=${JAVA_HOME}/jdk/bin:$PATH &&